services:
  db:
    build: .
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql_study
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql